<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lbw5von' shared service.

return $this->privates['.service_locator.lbw5von'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\HistoriqueController::index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
    'App\\Controller\\HistoriqueController:index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
], [
    'App\\Controller\\HistoriqueController::index' => '?',
    'App\\Controller\\HomeController::index' => '?',
    'App\\Controller\\HistoriqueController:index' => '?',
    'App\\Controller\\HomeController:index' => '?',
]);
