<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\HistoriqueController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\HistoriqueController.php';

$this->services['App\\Controller\\HistoriqueController'] = $instance = new \App\Controller\HistoriqueController(($this->privates['App\\Repository\\TaskRepository'] ?? $this->load('getTaskRepositoryService.php')), ($this->privates['App\\Repository\\TodoRepository'] ?? $this->load('getTodoRepositoryService.php')));

$instance->setContainer(($this->privates['.service_locator.CDOTD6.'] ?? $this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\Controller\\HistoriqueController', $this));

return $instance;
