<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._vzxoH4' shared service.

return $this->privates['.service_locator._vzxoH4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'task' => ['privates', '.errored..service_locator._vzxoH4.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator._vzxoH4": it references class "App\\Entity\\Task" but no such service exists.'],
], [
    'task' => 'App\\Entity\\Task',
]);
