<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6AiRum_' shared service.

return $this->privates['.service_locator.6AiRum_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Admin\\AdminTaskController::edit' => ['privates', '.service_locator._vzxoH4', 'get_ServiceLocator_VzxoH4Service.php', true],
    'App\\Controller\\Admin\\AdminTodoController::edit' => ['privates', '.service_locator.HWAlYHL', 'get_ServiceLocator_HWAlYHLService.php', true],
    'App\\Controller\\HistoriqueController::index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
    'App\\Controller\\Admin\\AdminTaskController:edit' => ['privates', '.service_locator._vzxoH4', 'get_ServiceLocator_VzxoH4Service.php', true],
    'App\\Controller\\Admin\\AdminTodoController:edit' => ['privates', '.service_locator.HWAlYHL', 'get_ServiceLocator_HWAlYHLService.php', true],
    'App\\Controller\\HistoriqueController:index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.Yrbq94C', 'get_ServiceLocator_Yrbq94CService.php', true],
], [
    'App\\Controller\\Admin\\AdminTaskController::edit' => '?',
    'App\\Controller\\Admin\\AdminTodoController::edit' => '?',
    'App\\Controller\\HistoriqueController::index' => '?',
    'App\\Controller\\HomeController::index' => '?',
    'App\\Controller\\Admin\\AdminTaskController:edit' => '?',
    'App\\Controller\\Admin\\AdminTodoController:edit' => '?',
    'App\\Controller\\HistoriqueController:index' => '?',
    'App\\Controller\\HomeController:index' => '?',
]);
