<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HWAlYHL' shared service.

return $this->privates['.service_locator.HWAlYHL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'todo' => ['privates', '.errored..service_locator.HWAlYHL.App\\Entity\\Todo', NULL, 'Cannot autowire service ".service_locator.HWAlYHL": it references class "App\\Entity\\Todo" but no such service exists.'],
], [
    'todo' => 'App\\Entity\\Todo',
]);
