<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Yrbq94C' shared service.

return $this->privates['.service_locator.Yrbq94C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'rep' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService.php', true],
    'todorep' => ['privates', 'App\\Repository\\TodoRepository', 'getTodoRepositoryService.php', true],
], [
    'rep' => 'App\\Repository\\TaskRepository',
    'todorep' => 'App\\Repository\\TodoRepository',
]);
