<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcjxcMH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcjxcMH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcjxcMH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcjxcMH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGcjxcMH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GcjxcMH',
    'container.build_id' => '0f2ae326',
    'container.build_time' => 1577024796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcjxcMH');
