<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH4wQxFt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH4wQxFt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH4wQxFt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH4wQxFt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH4wQxFt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H4wQxFt',
    'container.build_id' => '783d4d06',
    'container.build_time' => 1574178995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH4wQxFt');
