<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin.task.index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::getTasks'], [], [['text', '/api/task/getTasks']], [], []],
    'admin.task.index.id' => [['Name'], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::getTask'], [], [['variable', '/', '[^/]++', 'Name', true], ['text', '/api/task/getTask']], [], []],
    'admin.task.new' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::new'], [], [['text', '/api/task/create']], [], []],
    'task.delete' => [['Name'], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::deleteTask'], [], [['variable', '/', '[^/]++', 'Name', true], ['text', '/api/task/delete']], [], []],
    'app_admin_admintask_update' => [['Name'], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::update'], [], [['variable', '/', '[^/]++', 'Name', true], ['text', '/api/task/edit']], [], []],
    'todo.delete' => [['Name'], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::deleteTodo'], [], [['variable', '/', '[^/]++', 'Name', true], ['text', '/api/todo/delete']], [], []],
    'todo.getTodos' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::getTodos'], [], [['text', '/api/todo/getTodos']], [], []],
    'admin.todo.getTodos' => [['Name'], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::getTodo'], [], [['variable', '/', '[^/]++', 'Name', true], ['text', '/api/todo/getTodo']], [], []],
    'app_admin_admintodo_update' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/todo/update']], [], []],
    'admin.todo.new' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::new'], [], [['text', '/admin/todo/create']], [], []],
    'historique' => [[], ['_controller' => 'App\\Controller\\HistoriqueController::index'], [], [['text', '/historique']], [], []],
    'app_home_index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/api/home']], [], []],
    'app_home_create_task' => [[], ['_controller' => 'App\\Controller\\HomeController::create_Task'], [], [['text', '/api/create_task']], [], []],
    'todo1' => [[], ['_controller' => 'App\\Controller\\Todo1Controller::index'], [], [['text', '/todo1']], [], []],
];
