<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin.task.index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::index'], [], [['text', '/api/admin']], [], []],
    'admin.task.edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/task']], [], []],
    'admin.task.new' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTaskController::new'], [], [['text', '/api/admin/task/create']], [], []],
    'admin.todo.index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::index'], [], [['text', '/admin']], [], []],
    'admin.todo.edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/task']], [], []],
    'admin.todo.new' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminTodoController::new'], [], [['text', '/admin/task/create']], [], []],
    'historique' => [[], ['_controller' => 'App\\Controller\\HistoriqueController::index'], [], [['text', '/historique']], [], []],
    'app_home_index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/api/home']], [], []],
    'app_home_create_task' => [[], ['_controller' => 'App\\Controller\\HomeController::create_Task'], [], [['text', '/api/create_task']], [], []],
    'todo1' => [[], ['_controller' => 'App\\Controller\\Todo1Controller::index'], [], [['text', '/todo1']], [], []],
];
